In [270]:
import numpy as np
from typing import Tuple, Union

# Direct Method for Solving Linear Systems

## Chapter 6.1 Linear Systems of Equations

### Backward and Forward Substituition 
Given an augmented upper triangular matrix $U$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_n = \frac{u_{n, n+1}}{u_{n, n}}$$
$$x_i=\frac{1}{u_{i, i}}\biggl(u_{i, n+1}-\sum^{n}_{j=i+1}u_{i, j}x_{j}\biggr)$$
where $i=1,2,\cdots,n-1$

Given an augmented lower triangular matrix $L$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_1 = \frac{l_{1, n+1}}{l_{1, 1}}$$
$$x_i=\frac{1}{l_{i, i}}\biggl(l_{i, n+1}-\sum^{i - 1}_{j=1}l_{i, j}x_{j}\biggr)$$


In [271]:
def backSub(U:np.ndarray) -> np.ndarray:
    N, M = U.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[N - 1][0] = U[N - 1][M - 1] / U[N - 1][N - 1]    
    for jdx in range(N - 2, -1, -1):
        x[jdx] = (U[jdx][M - 1] - np.sum(U[jdx, jdx + 1:N] @ x[jdx + 1:])) / U[jdx][jdx]
    return x

def forSub(L:np.ndarray) -> np.ndarray:
    N, M = L.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[0][0] = L[0][M - 1] / L[0][0]   
    for jdx in range(1, N):
        x[jdx] = (L[jdx][M - 1] - np.sum(L[jdx, :jdx] @ x[:jdx])) / L[jdx][jdx]
    return x

In [272]:
def forwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    return backSub(A_) if not return_A else (A_, backSub(A_))

def backwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1, 0, -1):
        non_zero = np.nonzero(A_[:idx, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][::-1][0]
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx - 1, -1, -1):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[0][0] == 0:
        raise ValueError("No Unique Solution Exists...")
    return forSub(A_) if not return_A else (A_, forSub(A_))


In [273]:
A = np.array([
   [1, -1, 2, -1, -8],
   [2, -2, 3, -3, -20],
   [1, 1, 1, 0, -2],
   [1, -1, 4, 3, 4] 
], dtype=np.float32)

forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :4], A[:, -1])

(array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([-7.,  3.,  2.,  2.], dtype=float32))

In [274]:
A = np.random.randint(-50, 50, 42).reshape(6, 7)
print(A)
forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :6], A[:, -1])

[[ 35  25 -39  45 -39 -17 -30]
 [ 22   8 -50 -45 -11 -33  -2]
 [ 37  34 -19 -41 -41  28 -28]
 [ -7 -34  14 -49   1 -15 -35]
 [ -7 -35 -41  -4  40 -26   2]
 [ -7  32 -20 -19 -13 -15  21]]


(array([[ 0.75881105],
        [ 1.71771872],
        [ 0.79044198],
        [-0.08654563],
        [ 1.99271711],
        [-0.76096489]]),
 array([[ 0.75881105],
        [ 1.71771872],
        [ 0.79044198],
        [-0.08654563],
        [ 1.99271711],
        [-0.76096489]]),
 array([ 0.75881105,  1.71771872,  0.79044198, -0.08654563,  1.99271711,
        -0.76096489]))

## Chapter 6.4 The Determinant of a Matrix
> If B is a matrix obtained by multiplying a row of A by some non-zero constant ß, then
> - det(B) = ß * det(A)
> 
> In other words, you can essentially 'factor out' a constant from a row by just pulling it out front of the determinant.
> If B is a matrix obtained by swapping two rows of A, then
> 
> - det(B) = -det(A)
> 
> If you swap rows, flip the sign.
> If B is a matrix obtained by adding a multiple of one row to another row in A, then
> 
> - det(B) = det(A)
> 
> The determinant doesn't change.

Reference:[https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix](https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix)

The algorithm below implemented using the property that the determinant of the diagonal or triangular  matrix no matter lower or upper, the determinant is equal to $0$

So by using this property and the rule $(2\text{ and }3)$ above we come to the conclusion that $det(A)=(-1)^{m}\prod_{i}u_{i, i}$, where $u$ is the entry of the upper triangular matrix after reduce matrix $A$ to row echelon form and $m$ is the number of time we interchange the row.

In [275]:
def det(A:np.ndarray) -> float:
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    p = 0
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx

        # Row interchange causes sign of determinant flips
        if ptr != idx:
            A_[[idx, ptr]] = A_[[ptr, idx]]
            p += 1
            
        # Addition between row does not change the determinant
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    
    return np.prod(np.diag(A_)) * (-1) ** p

In [276]:
A = np.array([
   [1, -1, 2, -1],
   [2, -2, 3, -3],
   [1, 1, 1, 0],
   [1, -1, 4, 3] 
], dtype=np.float32)
det(A), np.linalg.det(A)

(4.0, 4.0)

In [277]:
A = np.random.randint(1, 20, 16).reshape((4, 4))
det(A), np.linalg.det(A)

(23199.000000000004, 23199.000000000015)

## Chapter 6.5 Matrix Factorization

### $LU$ and $PLU$ Decomposition

In [278]:
def LU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    '''
    Returns:
    L: The lower triangular matrix obtained with main diagonal elements = 1
    U: The upper triangular matrix obtained
    '''

    if A[0][0] == 0:
        raise ValueError("Factorization impossible")
    
    N = A.shape[0]
    L = np.eye(N)
    U = np.zeros_like(A, dtype=float)
    A_ = np.copy(A).astype(float)

    for idx in range(N):
        if A_[idx][idx] - (L[idx, :idx] @ U[idx, :idx]) == 0:
            raise ValueError("Factorization impossible")
        # When idx = 0, L[0, :0] and U[:0, 0] are both empty arrays and @ two empty arrays result in 0.0
        U[idx][idx] = A_[idx][idx] - (L[idx, :idx] @ U[:idx, idx])
        for jdx in range(idx + 1, N):
            U[idx][jdx] = (A_[idx][jdx] - L[idx, :idx] @ U[:idx, jdx]) / L[idx][idx]
            L[jdx][idx] = (A_[jdx][idx] - L[jdx, :idx] @ U[:idx, idx]) / U[idx][idx]
    return L, U

In [279]:
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)
L, U = LU(A)
L @ U

array([[ 1.,  1.,  0.,  3.],
       [ 2.,  1., -1.,  1.],
       [ 3., -1., -1.,  2.],
       [-1.,  2.,  3., -1.]])

In [280]:
def PLU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    '''
    PA = LU
    This method derived from the Gaussian Elimnation process
    Returns:
    P: The transposed permutation matrix so that A = PLU
    L: The lower triangular matrix obtained with main diagonal elements = 1
    U: The upper triangular matrix obtained
    '''
    N = A.shape[0]
    P = np.eye(N)
    L = np.zeros_like(A, dtype=float)
    U = np.copy(A).astype(float)
    
    for idx in range(N - 1):
        pivot_row = np.argmax(np.abs(U[idx:, idx])) + idx
        # (E_i <--> E_j)
        if pivot_row != idx:
            P[[idx, pivot_row]] = P[[pivot_row, idx]]
            U[[idx, pivot_row]] = U[[pivot_row, idx]]
            L[[idx, pivot_row]] = L[[pivot_row, idx]]
        for jdx in range(idx + 1, N):
            factor = U[jdx, idx] / U[idx, idx]
            L[jdx, idx] = factor
            # (E_i + mE_j) --> (E_i)
            U[jdx, :] -= factor * U[idx, :]
    np.fill_diagonal(L, 1)
    return P.T, L, U

In [281]:
A = np.array([
    [0, 0, -1, 1],
    [1, 1, -1, 2],
    [-1, -1, 2, 0],
    [1, 2, 0, 2]
])
P, L, U = PLU(A)
P @ L @ U

array([[ 0.,  0., -1.,  1.],
       [ 1.,  1., -1.,  2.],
       [-1., -1.,  2.,  0.],
       [ 1.,  2.,  0.,  2.]])

### $LDL^T$ Decomposition amd its pivoting version
Pseudocode of pivoting version is not available in _Numerical Analysis by Richard L. Burden_ but _Matrix Computation by G.H. Golub_

In [282]:
def LDL(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    '''
    A = LDLT
    Returns:
    L: The lower triangular matrix obtained with main diagonal elements = 1
    D The diagonal matrix obtained
    '''
    N = A.shape[0]
    L = np.eye(N)
    D = np.zeros(N)
    v = np.zeros(N)
    for idx in range(N):
        for jdx in range(idx):
            v[jdx] = L[idx, jdx] * D[jdx]
        D[idx] = A[idx][idx] - L[idx, :idx] @ v[:idx]
        for jdx in range(idx + 1, N):
            L[jdx][idx] = (A[jdx][idx] - L[jdx, :idx] @ v[:idx])  / D[idx]
    D_ = np.zeros((N, N))
    D_[np.diag_indices(N)] = D
    return L, D_

In [283]:
A = np.array([
    [4, -1, 1],
    [-1, 4.25, 2.75],
    [1, 2.75, 3.5]
])
L, D = LDL(A)

L @ D @ L.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])

In [284]:
def PLDL(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    '''
    PAPT = LDLT
    Returns:
    P: The transposed permutation matrix
    L: The lower triangular matrix obtained with main diagonal elements = 1
    D The diagonal matrix obtained
    '''
    N = A.shape[0]
    P = np.eye(N)
    A_ = np.copy(A).astype(float)

    for idx in range(N):
        piv = np.argmax(np.diag(A_[idx:, idx:])) + idx
        P[[idx, piv]] = P[[piv, idx]]
        A_[[idx, piv]] = A_[[piv, idx]]
        A_[:, [idx, piv]] = A_[:, [piv, idx]]
        alpha = A_[idx, idx]
        v = np.copy(A_[idx + 1:, idx])
        A_[idx + 1:, idx] = v / alpha
        A_[idx + 1:, idx + 1:] -= np.outer(v, v) / alpha

    D = np.zeros((N, N))
    D[np.diag_indices(N)] = np.diag(A_)
    L =np.tril(A_, k=-1) + np.eye(N)
    return P, L, D

In [285]:
A = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])
P, L, D = PLDL(A)
P.T @ L @ D @ L.T @ P

array([[1., 2., 3.],
       [2., 4., 5.],
       [3., 5., 6.]])

### Cholesky Decoomposition

In [286]:
def cho(A:np.ndarray) -> np.ndarray:
    N = A.shape[0]
    L = np.zeros((N, N))
    for idx in range(N):
        L[idx][idx] = np.sqrt(A[idx][idx] - np.sum(L[idx, :idx] ** 2))
        for jdx in range(idx + 1, N):
            L[jdx][idx] = (A[jdx][idx] - L[jdx, :idx] @ L[idx, :idx]) / L[idx][idx]
    return L

In [287]:
A = np.array([
    [4, -1, 1],
    [-1, 4.25, 2.75],
    [1, 2.75, 3.5]
])
L = cho(A)
L @ L.T

array([[ 4.  , -1.  ,  1.  ],
       [-1.  ,  4.25,  2.75],
       [ 1.  ,  2.75,  3.5 ]])