In [620]:
import numpy as np
from typing import Tuple, Union

# Direct Method for Solving Linear Systems

## Chapter 6.1 Linear Systems of Equations

### Backward and Forward Substituition 
Given an augmented upper triangular matrix $U$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_n = \frac{u_{n, n+1}}{u_{n, n}}$$
$$x_i=\frac{1}{u_{i, i}}\biggl(u_{i, n+1}-\sum^{n}_{j=i+1}u_{i, j}x_{j}\biggr)$$
where $i=1,2,\cdots,n-1$

Given an augmented lower triangular matrix $L$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_1 = \frac{l_{1, n+1}}{l_{1, 1}}$$
$$x_i=\frac{1}{l_{i, i}}\biggl(l_{i, n+1}-\sum^{i - 1}_{j=1}l_{i, j}x_{j}\biggr)$$


In [621]:
def backSub(U:np.ndarray) -> np.ndarray:
    N, M = U.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[N - 1][0] = U[N - 1][M - 1] / U[N - 1][N - 1]    
    for jdx in range(N - 2, -1, -1):
        x[jdx] = (U[jdx][M - 1] - np.sum(U[jdx, jdx + 1:N] @ x[jdx + 1:])) / U[jdx][jdx]
    return x

def forSub(L:np.ndarray) -> np.ndarray:
    N, M = L.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[0][0] = L[0][M - 1] / L[0][0]   
    for jdx in range(1, N):
        x[jdx] = (L[jdx][M - 1] - np.sum(L[jdx, :jdx] @ x[:jdx])) / L[jdx][jdx]
    return x

In [622]:
def forwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    return backSub(A_) if not return_A else (A_, backSub(A_))

def backwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1, 0, -1):
        non_zero = np.nonzero(A_[:idx, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][::-1][0]
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx - 1, -1, -1):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[0][0] == 0:
        raise ValueError("No Unique Solution Exists...")
    return forSub(A_) if not return_A else (A_, forSub(A_))


In [623]:
A = np.array([
   [1, -1, 2, -1, -8],
   [2, -2, 3, -3, -20],
   [1, 1, 1, 0, -2],
   [1, -1, 4, 3, 4] 
], dtype=np.float32)

forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :4], A[:, -1])

(array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([-7.,  3.,  2.,  2.], dtype=float32))

In [624]:
A = np.random.randint(-50, 50, 42).reshape(6, 7)
print(A)
forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :6], A[:, -1])

[[-19 -42   1 -20 -11  21 -18]
 [-15  -8  16 -14 -43  45  28]
 [ 19 -35   8 -31  39  48   5]
 [-41  37  34  14   3 -34  10]
 [ -9  38   4  26 -31  37  30]
 [-15 -49  -7  -3 -12  35  43]]


(array([[ 2.74051024],
        [-2.4884594 ],
        [ 4.55662652],
        [ 4.12018086],
        [-0.93245991],
        [-0.13598422]]),
 array([[ 2.74051024],
        [-2.4884594 ],
        [ 4.55662652],
        [ 4.12018086],
        [-0.93245991],
        [-0.13598422]]),
 array([ 2.74051024, -2.4884594 ,  4.55662652,  4.12018086, -0.93245991,
        -0.13598422]))

## Chapter 6.4 The Determinant of a Matrix
> If B is a matrix obtained by multiplying a row of A by some non-zero constant ß, then
> - det(B) = ß * det(A)
> 
> In other words, you can essentially 'factor out' a constant from a row by just pulling it out front of the determinant.
> If B is a matrix obtained by swapping two rows of A, then
> 
> - det(B) = -det(A)
> 
> If you swap rows, flip the sign.
> If B is a matrix obtained by adding a multiple of one row to another row in A, then
> 
> - det(B) = det(A)
> 
> The determinant doesn't change.

Reference:[https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix](https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix)

The algorithm below implemented using the property that the determinant of the diagonal or triangular  matrix no matter lower or upper, the determinant is equal to $0$

So by using this property and the rule $(2\text{ and }3)$ above we come to the conclusion that $det(A)=(-1)^{m}\prod_{i}u_{i, i}$, where $u$ is the entry of the upper triangular matrix after reduce matrix $A$ to row echelon form and $m$ is the number of time we interchange the row.

In [625]:
def det(A:np.ndarray) -> float:
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    p = 0
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx

        # Row interchange causes sign of determinant flips
        if ptr != idx:
            A_[[idx, ptr]] = A_[[ptr, idx]]
            p += 1
            
        # Addition between row does not change the determinant
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    
    return np.prod(np.diag(A_)) * (-1) ** p

In [626]:
A = np.array([
   [1, -1, 2, -1],
   [2, -2, 3, -3],
   [1, 1, 1, 0],
   [1, -1, 4, 3] 
], dtype=np.float32)
det(A), np.linalg.det(A)

(4.0, 4.0)

In [627]:
A = np.random.randint(1, 20, 16).reshape((4, 4))
det(A), np.linalg.det(A)

(-17797.999999999993, -17797.999999999996)

## Chapter 6.5 Matrix Factorization

### LU and PLU Decomposition

In [628]:
def LU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    '''
    Returns:
    L: The lower triangular matrix obtained with main diagonal elements = 1
    U: The upper triangular matrix obtained
    '''

    if A[0][0] == 0:
        raise ValueError("Factorization impossible")
    
    N = A.shape[0]
    L = np.eye(N)
    U = np.zeros_like(A, dtype=float)
    A_ = np.copy(A).astype(float)

    for idx in range(N):
        if A_[idx][idx] - (L[idx, :idx] @ U[idx, :idx]) == 0:
            raise ValueError("Factorization impossible")
        # When idx = 0, L[0, :0] and U[:0, 0] are both empty arrays and @ two empty arrays result in 0.0
        U[idx][idx] = A_[idx][idx] - (L[idx, :idx] @ U[:idx, idx])
        for jdx in range(idx + 1, N):
            U[idx][jdx] = (A_[idx][jdx] - L[idx, :idx] @ U[:idx, jdx]) / L[idx][idx]
            L[jdx][idx] = (A_[jdx][idx] - L[jdx, :idx] @ U[:idx, idx]) / U[idx][idx]
    return L, U

In [629]:
A = np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)
L, U = LU(A)
L @ U

array([[ 1.,  1.,  0.,  3.],
       [ 2.,  1., -1.,  1.],
       [ 3., -1., -1.,  2.],
       [-1.,  2.,  3., -1.]])

In [630]:
def PLU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    '''
    PA = LU
    This method derived from the Gaussian Elimnation process
    Returns:
    P: The transposed permutation matrix so that A = PLU
    L: The lower triangular matrix obtained with main diagonal elements = 1
    U: The upper triangular matrix obtained
    '''
    N = A.shape[0]
    P = np.eye(N)
    L = np.zeros_like(A)
    U = np.copy(A).astype(float)
    
    for idx in range(N - 1):
        pivot_row = np.argmax(np.abs(U[idx:, idx])) + idx
        # (E_i <--> E_j)
        if pivot_row != idx:
            P[[idx, pivot_row]] = P[[pivot_row, idx]]
            U[[idx, pivot_row]] = U[[pivot_row, idx]]
            L[[idx, pivot_row]] = L[[pivot_row, idx]]
        for jdx in range(idx + 1, N):
            factor = U[jdx, idx] / U[idx, idx]
            L[jdx, idx] = factor
            # (E_i + mE_j) --> (E_i)
            U[jdx, :] -= factor * U[idx, :]
    np.fill_diagonal(L, 1)
    return P.T, L, U

In [631]:
A = np.array([
    [0, 0, -1, 1],
    [1, 1, -1, 2],
    [-1, -1, 2, 0],
    [1, 2, 0, 2]
])
P, L, U = PLU(A)
P @ L @ U

array([[ 0.,  0., -1.,  1.],
       [ 1.,  1., -1.,  2.],
       [-1., -1.,  2.,  0.],
       [ 1.,  2.,  0.,  2.]])