In [553]:
import numpy as np
import math
from typing import Callable, Union, Tuple, List, Any
import pandas as pd

# Initial-Value Problems for Ordinary Differential Equations

## Chapter 5.2 Euler's Method
Given 
$$ \frac{dy}{dt} = f(t, y),\,\,\, a\leq t\leq b,\,\,\,y(a)=\alpha $$
and consider
$$ t_i = a+ih,\,\,\,i=0,1,2\cdots,N$$
Suppose $y(t)$ has two continuous derivatives on $[a, b]$, then by Taylor's Theorem
$$ y(t_{i+1})=y(t_i)+(t_{i+1}-t_i)y'(t_i)+\frac{(t_{i+1}-t_i)^2}{2}y''(\xi_i) $$
because $h=t_{i+1}-t_i$, then
$$ y(t_{i+1})=y(t_i)+hf(t_i,y(t_i))+\frac{h^2}{2}y''(\xi_i)$$

The definition of $t_i$ and $h$ are the same throughout the context.

Euler's method constructs $w_i\approx y(t_i)$, by deleting the remainder term. In short,
$$w_0=\alpha$$
$$w_{i+1}=w_i+hf(t_i, w_i),\,\,\,i=0, 1,\cdots,N-1$$

In [554]:
def Euler(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
          a:Union[float, int],
          b:Union[float, int],
          alpha:Union[float, int],
          h:Union[float, int]=None,
          N:int=None,
         ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * alpha
    for idx in range(1, N + 1):
        w_[idx] =  w_[idx - 1] + h * f(t_[idx - 1], w_[idx - 1])
    return (t_, w_)

In [555]:
f = lambda t, y: y - t ** 2 + 1
Euler(f, 0, 2, 0.5, h=0.5)

(array([0. , 0.5, 1. , 1.5, 2. ]),
 array([0.5   , 1.25  , 2.25  , 3.375 , 4.4375]))

In [556]:
f = lambda t, y: np.cos(2 * t) + np.sin(3 * t)
Euler(f, 0, 1, 1, N=4)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([1.        , 1.25      , 1.63980533, 2.02425465, 2.23645725]))

## Chapter 5.3 Higher-Order Taylor Methods
Suppose the solution $y(t)$ to the initial-value problem
$$ \frac{dy}{dt} = f(t, y),\,\,\, a\leq t\leq b,\,\,\,y(a)=\alpha $$
has $(n+1)$ continuous derivatives. By its $n$th Taylor polynomial about $t_i$ and evaluate at $t_{i+1}$,
$$y(t_{{i+1}})=y(t_i)+hy'(t_i)+\frac{h^2}{2}y''(t_i)+\cdots+\frac{h^n}{n!}y^{(n)}(t_i)+\frac{h^{n+1}}{(n+1)!}y^{(n+1)}(\xi_i)$$
for some $\xi_i\in(t_i, t_{i+1})$
Successive differentiation of the solution, $y(t)$ gives
$$y'(t)=f(t, y(t)),\,\,\,y''(t)=f'(t, y(t)),\,\,\,\text{ and generally, }\,\,\, y^{(k)}(t)=f^{(k-1)}(t, y(t))$$
Substituting these findings into previous equations gives
$$y(t_{{i+1}})=y(t_i)+hf(t_i)+\frac{h^2}{2}f'(t_i)+\cdots+\frac{h^n}{n!}f^{(n - 1)}(t_i)+\frac{h^{n+1}}{(n+1)!}f^{(n)}(\xi_i)$$
Similar to Euler's method, in short
$$w_0=\alpha$$
$$w_{i+1}=w_i+hT^{(n)}(t_i, w_i),\,\,\,i=0,1,\cdots,N-1$$
where
$$T^{(n)}(t_i, w_i)=\sum^{n-1}_{i=0}\frac{h^{i}}{(i+1)!}f^{(i)}(t_i, w_i)$$
Euler's method is Taylor's method of order one.

In [557]:
def Taylor(func:List[Callable[[Union[float, int], Union[float, int]], Union[float, int]]],
           a:Union[float, int],
           b:Union[float, int],
           alpha:Union[float, int],
           h:Union[float, int]=None,
           N:int=None
          ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * alpha
    
    for idx in range(1, N + 1):
        T = sum([(h ** jdx) * f(t_[idx - 1], w_[idx - 1]) / math.factorial(jdx + 1) for jdx, f in enumerate(func)])
        w_[idx] = w_[idx - 1] + h * T
    return (t_, w_)

In [558]:
f = [
    lambda t, y: y - t ** 2 + 1,
    lambda t, y: y - t ** 2 + 1 - 2 * t
]
Taylor(f, 0, 2, 0.5, 0.2)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 array([0.5       , 0.83      , 1.2158    , 1.652076  , 2.13233272,
        2.64864592, 3.19134802, 3.74864458, 4.30614639, 4.8462986 ,
        5.34768429]))

## Chapter 5.4 Runge-Kutta Methods
__Runge-Kutta methods__ have the high-order local truncation error of the Taylor methods
but eliminate the need to compute and evaluate the derivatives of $f (t, y)$

In general, __Runge-Kutta Methods__ have the following form:
$$
y_{i+1} = y_i+h\sum_{i=1}^{s}b_ik_i
$$
where
$y_i=y(t_i)$

$k_1=f(t_i,y_i)$

$k_2=f(t_i+c_2h,y_i+(a_{21}k_1)h)$

$k_3=f(t_i+c_3h,y_i+(a_{31}k_1+a_{32}k_2)h)$

$\vdots$

$k_s=f(t_i+c_sh,y_i+(a_{s1}k_1+a_{s2}k_2+\cdots+a_{s, s-1}k_{s-1})h)$

The parameters above can be store as an matrix where the illustrated as below:
\begin{bmatrix}
0 & 0 & 0 & \cdots & 0\\
c_2 & a_{21} & a_{22} & \cdots & a_{s2}\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
c_s & a_{s1} & a_{s2} & \cdots & a_{ss}\\
0 & b_1 & b_2 & \cdots & b_s
\end{bmatrix}	

The matrix $[a_{ij}]$ is called the Runge-Kutta matrix while $b_i$ and $c_i$ are known as the weights and the nodes.

Refer to [Wikipedia](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods) for more information

### Runge-Kutta Methods of Order Two
There is a family of such methods, parameterized by α and given by the formula
$$
y(t_{i+1})=y(t_i)+h\biggl(\biggl(1-\frac{1}{2\alpha}f(t_i, y(t_i))\biggr)+\frac{1}{2\alpha}f(t_i+\alpha h, y(t_i)+\alpha f(t_i, y(t_i)))\biggr)
$$
where 
$\alpha=\frac{1}{2}$ gives the midpoint method, $\alpha=1$ is Modified Euler Method(Heun's method), and $\alpha=\frac{2}{3}$ is Ralston's method.

So by the matrix notation introduced above, we have
\begin{bmatrix}
0 & 0 & 0\\
\alpha & \alpha & 0\\
0 & 1 - \frac{1}{2\alpha} & \frac{1}{2\alpha}
\end{bmatrix}	


#### Midpoint Method
$w_0=\alpha$

$w_{i+1}=w_i+hf\biggl(t_i+\frac{h}{2}, w_i+\frac{h}{2}f(t_i, w_i)\biggr),\,\,\,i=0, 1,\cdots,N-1$

#### Modified Euler Method
$w_0=\alpha$

$w_{i+1}=w_i+\frac{h}{2}[f(t_i, w_i)+f(t_{i+1}, w_i+hf(t_i, w_i))],\,\,\,i=0, 1,\cdots,N-1$

#### Ralston's Method
$w_0=\alpha$

$w_{i+1}=w_i+h\biggl[\frac{1}{4}f(t_i, w_i)+\frac{3}{4}f(t_{i+1}+\frac{2}{3}h, w_i+\frac{2}{3}hf(t_i, w_i))\biggr],\,\,\,i=0, 1,\cdots,N-1$

In [559]:
def RK2_Generic(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
          a:Union[float, int],
          b:Union[float, int],
          y_init:Union[float, int],
          h:Union[float, int]=None,
          alpha:float=0.5,
          N:int=None,
         ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * y_init
    for idx in range(1, N + 1):
        w_[idx] =  w_[idx - 1] + h * ((1 - 1 / (2 * alpha)) * f(t_[idx - 1], w_[idx - 1]) + 
                                      (f(t_[idx - 1] + alpha * h, w_[idx - 1] + alpha * h * f(t_[idx - 1], w_[idx - 1]))) / (2 * alpha)
                                      )
    return (t_, w_)

### Runge-Kutta Methods of Order Three
#### Heun's Method

$w_0=\alpha$

$w_{i+1}=w_i+\frac{h}{4}\biggl[f(t_i, w_i)+3f(t_{i}+\frac{2}{3}h, w_i+\frac{2}{3}hf(t_i+\frac{1}{3}h, w_i+\frac{1}{3}f(t_i, w_i)))\biggr],\,\,\,i=0, 1,\cdots,N-1$

In [560]:
def Heun(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
          a:Union[float, int],
          b:Union[float, int],
          y_init:Union[float, int],
          h:Union[float, int]=None,
          N:int=None,
         ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * y_init
    for idx in range(1, N + 1):
        w_[idx] =  w_[idx - 1] + h * (f(t_[idx - 1], w_[idx - 1]) + 3 * f(t_[idx - 1] + (2 / 3) * h, w_[idx - 1] + (2 / 3) * 
                                        h * f(t_[idx - 1] + (1 / 3) * h, w_[idx - 1] + (1 / 3) * h *  f(t_[idx - 1], w_[idx - 1])))) / 4
    return (t_, w_)

### Runge-Kutta Methods of Order Four (Most commonly used)

$w_0=\alpha$

$k_1=hf(t_i, w_i)$

$k_2=hf\biggl(t_i+\frac{h}{2}, w_i+\frac{1}{2}k_1\biggr)$

$k_3=hf\biggl(t_i+\frac{h}{2}, w_i+\frac{1}{2}k_2\biggr)$

$k_4=hf(t_{i+1}, w_i+k_3)$

$w_{i+1}=\frac{1}{6}(k_1+2k_2+2k_3+k_4)$

for each $i=0, 1,\cdots,N-1$

In [561]:
def RK4(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
        a:Union[float, int],
        b:Union[float, int],
        y_init:Union[float, int],
        h:Union[float, int]=None,
        N:int=None,
        ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * y_init
    for idx in range(1, N + 1):
        k_1 = h * f(t_[idx - 1], w_[idx - 1])
        k_2 = h * f(t_[idx - 1] + h / 2, w_[idx - 1] + k_1 / 2)
        k_3 = h * f(t_[idx - 1] + h / 2, w_[idx - 1] + k_2 / 2)
        k_4 = h * f(t_[idx], w_[idx - 1] + k_3)
        w_[idx] = w_[idx - 1] + (k_1 + 2 * k_2 + 2 * k_3 + k_4) / 6
    return (t_, w_)

#### Implementation of General Runge-Kutta Methods
In convinient, the implementation of the function will take $[a_{ij}]$ as a numpy matrix while $b_i$ and $c_i$ will be 1-D numpy array known as parameter _rk_mat_, _weights_, _nodes_ respectively

In [562]:
def RK(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
       a:Union[float, int],
       b:Union[float, int],
       rk_mat:np.ndarray[Union[float, int], Any],
       weights:np.ndarray[Union[float, int], Any],
       nodes:np.ndarray[Union[float, int], Any],
       y_init:Union[float, int],
       h:Union[float, int]=None,
       N:int=None,
        ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)
    if rk_mat.shape[0] != nodes.shape[0]:
        raise ValueError("The number of row of rk_mat not equal to the size of nodes...")
    if rk_mat.shape[1] != weights.shape[0]:
        raise ValueError("The number of column of rk_mat not equal to the size of weights...")
    
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, )) * y_init
    for idx in range(1, N + 1):
        k_ = np.zeros((weights.shape[0], ), dtype=float)
        k_[0] = f(t_[idx - 1], w_[idx - 1])
        for jdx in range(1, weights.shape[0]):
            k_[jdx] += f(t_[idx - 1] + nodes[jdx - 1] * h, w_[idx - 1] + (rk_mat[jdx - 1] @ k_) * h)
        w_[idx] =  w_[idx - 1] + h * np.sum(k_ * weights)
    return (t_, w_)
    

In [563]:
f = lambda t, y: y - t ** 2 + 1

t_1, w_1 = RK2_Generic(f, 0, 2, 0.5, 0.2, alpha=0.5)
t_2, w_2 = RK2_Generic(f, 0, 2, 0.5, 0.2, alpha=1)
t_3, w_3 = RK2_Generic(f, 0, 2, 0.5, 0.2, alpha=2 / 3)
t_4, w_4 = Heun(f, 0, 2, 0.5, 0.2)
t_5, w_5 = RK4(f, 0, 2, 0.5, 0.2)


midpoint_rk = np.array([[0.5, 0]])
midpoint_c = np.array([0.5])
midpoint_b = np.array([0, 1])

modified_euler_rk = np.array([[1, 0]])
modified_euler_c = np.array([1])
modified_euler_b = np.array([0.5, 0.5])

ralston_rk = np.array([[2 / 3, 0]])
ralston_c = np.array([2 / 3])
ralston_b = np.array([1 / 4, 3 / 4])

heun3_rk = np.array([[1 / 3, 0, 0], [0, 2 / 3, 0]])
heun3_c = np.array([1 / 3, 2 / 3])
heun3_b = np.array([1 / 4, 0, 3 / 4])

RK4_rk = np.array([[1 / 2, 0, 0, 0], [0, 1 / 2, 0, 0], [0, 0, 1, 0]])
RK4_c = np.array([1 / 2, 1 / 2, 1])
RK4_b = np.array([1 / 6, 1 / 3, 1 / 3, 1 / 6])

t_6, w_6 = RK(f, 0, 2, midpoint_rk, midpoint_b, midpoint_c, 0.5, 0.2)
t_7, w_7 = RK(f, 0, 2, modified_euler_rk, modified_euler_b, modified_euler_c, 0.5, 0.2)
t_8, w_8 = RK(f, 0, 2, ralston_rk, ralston_b, ralston_c, 0.5, 0.2)
t_9, w_9 = RK(f, 0, 2, heun3_rk, heun3_b, heun3_c, 0.5, 0.2)
t_10, w_10 = RK(f, 0, 2, RK4_rk, RK4_b, RK4_c, 0.5, 0.2)


# The methods with _ at the end means that the values computed using
# the general formula
pd.DataFrame(
    {
        "t":t_1,
        "Midpoint":w_1,
        "Midpoint_":w_5,
        "Modified Euler":w_2,
        "Modified Euler_":w_6,
        "Ralston":w_3,
        "Ralston_":w_7,
        "Heun":w_4,
        "Heun_":w_8,
        "RK4":w_5,
        "RK4_":w_10
    }
)


t  Midpoint  Midpoint_  Modified Euler  Modified Euler_   Ralston  \
0   0.0  0.500000   0.500000        0.500000         0.500000  0.500000   
1   0.2  0.828000   0.829293        0.826000         0.828000  0.827333   
2   0.4  1.211360   1.214076        1.206920         1.211360  1.209880   
3   0.6  1.644659   1.648922        1.637242         1.644659  1.642187   
4   0.8  2.121284   2.127203        2.110236         2.121284  2.117601   
5   1.0  2.633167   2.640823        2.617688         2.633167  2.628007   
6   1.2  3.170463   3.179894        3.149579         3.170463  3.163502   
7   1.4  3.721165   3.732340        3.693686         3.721165  3.712006   
8   1.6  4.270622   4.283409        4.235097         4.270622  4.258780   
9   1.8  4.800959   4.815086        4.755619         4.800959  4.785845   
10  2.0  5.290369   5.305363        5.233055         5.290369  5.271265   

    Ralston_      Heun     Heun_       RK4      RK4_  
0   0.500000  0.500000  0.500000  0.500000  0.500000  
1   0.826000  0.829244  0.827333  0.829293  0.829293  
2   1.206920  1.213975  1.209880  1.214076  1.214076  
3   1.637242  1.648766  1.642187  1.648922  1.648922  
4   2.110236  2.126991  2.117601  2.127203  2.127203  
5   2.617688  2.640556  2.628007  2.640823  2.640823  
6   3.149579  3.179576  3.163502  3.179894  3.179894  
7   3.693686  3.731980  3.712006  3.732340  3.732340  
8   4.235097  4.283023  4.258780  4.283409  4.283409  
9   4.755619  4.814697  4.785845  4.815086  4.815086  
10  5.233055  5.305007  5.271265  5.305363  5.305363

## Chapter 5.5 Error Control and the Runge-Kutta-Fehlberg Method

In [564]:
def RKEmbedded(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
            a:Union[float, int],
            b:Union[float, int],
            rk_mat:np.ndarray[Union[float, int], Any],
            weights:np.ndarray[Union[float, int], Any],
            weights_:np.ndarray[Union[float, int], Any],
            nodes:np.ndarray[Union[float, int], Any],
            y_init:Union[float, int],
            h_max:Union[float, int],
            h_min:Union[float, int],
            n:int,
            delta_coef:float,
            tol:float=1e-6,
        ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:

    if rk_mat.shape[0] != nodes.shape[0]:
        raise ValueError("The number of row of rk_mat not equal to the size of nodes...")
    if rk_mat.shape[1] != weights.shape[0]:
        raise ValueError("The number of column of rk_mat not equal to the size of weights...")
    
    h = h_max
    t_, w_ = [a], [y_init]
    t = a
    idx = 1
    while True:
        k_ = np.zeros((weights.shape[0], ), dtype=float)
        k_[0] = f(t, w_[idx - 1])
        for jdx in range(1, weights.shape[0]):
            k_[jdx] += f(t + nodes[jdx - 1] * h, w_[idx - 1] + (rk_mat[jdx - 1] @ k_) * h)
        R = abs((h * np.sum(k_ * weights)) - (h * np.sum(k_ * weights_))) / h
        if R <= tol:
            t = t_[idx - 1] + h
            t_.append(t)
            w_.append(w_[idx - 1] + h * np.sum(k_ * weights))
            idx += 1
        delta = delta_coef * (tol / R) ** (1 / n)
        if delta <= 0.1:
            delta = 0.1
        elif delta >= 4:
            delta = 4
        h *= delta
        h = min(h, h_max)
        if t >= b:
            return (np.array(t_), np.array(w_))
        elif t + h > b:
            h = b - t
        elif h < h_min:
            return (np.array(t_), np.array(w_))
    

In [565]:
RKF_rk = np.array([
    [0.25, 0, 0, 0, 0, 0], [3 / 32, 9 / 32, 0, 0, 0, 0],
    [1932 / 2197, -7200 / 2197, 7296 / 2197, 0, 0, 0],
    [439 / 216, -8, 3680 / 513, -845 / 4104, 0, 0],
    [-8 / 27, 2, -3544 / 2565, 1859 / 4104, -11 / 40, 0]
    ])
RKF_c = np.array([1 / 4, 3 / 8, 12 / 13, 1, 1 / 2])
RKF_bp = np.array([16 / 135, 0, 6656 / 12825, 28561 / 56430, -9 / 50, 2 / 55])
RKF_b = np.array([25 / 216, 0, 1408 / 2565, 2197 / 4104, -1 / 5, 0])

f = lambda t, y: y - t ** 2 + 1
RKEmbedded(f, 0, 2, RKF_rk, RKF_b, RKF_bp, RKF_c, 0.5, 0.25, 0.01, 4, 0.84, 0.00001)

(array([0.       , 0.25     , 0.4865522, 0.7293332, 0.9793332, 1.2293332,
        1.4793332, 1.7293332, 1.9793332, 2.       ]),
 array([0.5       , 0.9204886 , 1.39649101, 1.95374879, 2.58642601,
        3.26046051, 3.95209554, 4.63082682, 5.25748606, 5.30548963]))

## Chapter 5.6 Multistep Methods

In [566]:
# Compute the coefficients of f in the Adams-Bashforth and Adams-Moulton methods

def BackwardDiffCoef(k:int):
    Q = np.zeros((k, k))
    Q[0, 0] = 1
    for idx in range(k - 1):
        for jdx in range(k - 1):
            if Q[idx, jdx] != 0:
                Q[idx, jdx + 1] += 1 * Q[idx, jdx]
                Q[idx + 1, jdx + 1] -= 1 * Q[idx, jdx]
    return Q

def ForwardDiffCoef(k:int):
    Q = np.zeros((k, k))
    Q[0, 0] = 1
    for idx in range(k - 1):
        for jdx in range(k - 1):
            if Q[idx, jdx] != 0:
                Q[idx, jdx + 1] -= 1 * Q[idx, jdx]
                Q[idx + 1, jdx + 1] += 1 * Q[idx, jdx]
    return Q

def CombCoef(m:int, backward:bool=True) -> np.ndarray:
    coef = np.ones((m, ))
    for mdx in range(1, m):
        roots = np.arange(mdx)
        poly = np.polynomial.Polynomial.fromroots(-roots if backward else roots)
        anti_poly = poly.integ()
        coef[mdx] = (anti_poly(1) - anti_poly(0)) / math.factorial(mdx)
    return coef

def MultiStepCoef(m:int, backward:bool=True) -> np.ndarray:
    if backward:
        return (CombCoef(m) * BackwardDiffCoef(m)).sum(axis=1)
    return (CombCoef(m, backward) * ForwardDiffCoef(m)).sum(axis=1)


In [567]:
print("Adam-Bashforth")
for idx in range(2, 6):
    print(MultiStepCoef(idx))
print("Adam-Moulton")
for idx in range(3, 6):
    print(MultiStepCoef(idx, False))

print("Adam-Bashforth Coefficient for LTE")
for idx in range(2, 6):
    print(abs(MultiStepCoef(idx + 1)[-1]))
print("Adam-Moulton Coefficient for LTE")
for idx in range(3, 6):
    print(-abs(MultiStepCoef(idx + 1, False)[-1]))


Adam-Bashforth
[ 1.5 -0.5]
[ 1.91666667 -1.33333333  0.41666667]
[ 2.29166667 -2.45833333  1.54166667 -0.375     ]
[ 2.64027778 -3.85277778  3.63333333 -1.76944444  0.34861111]
Adam-Moulton
[ 0.41666667  0.66666667 -0.08333333]
[ 0.375       0.79166667 -0.20833333  0.04166667]
[ 0.34861111  0.89722222 -0.36666667  0.14722222 -0.02638889]
Adam-Bashforth Coefficient for LTE
0.41666666666666663
0.375
0.34861111111111115
0.3298611111111111
Adam-Moulton Coefficient for LTE
-0.041666666666666664
-0.026388888888888906
-0.01875


### General Adams-Bashforth Methods

In [568]:
def AdamsBashforth(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
       a:Union[float, int],
       b:Union[float, int],
       y_init:Union[float, int],
       h:Union[float, int]=None,
       m:int=None,
       N:int=None,
       helper:callable=RK4,
       ) -> float:
    
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)

    coef = MultiStepCoef(m)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, ))
    w_[:m] = helper(f, a, b, y_init, h)[1][:m]
    
    for idx in range(m, N + 1):
        f_val = np.array([f(t_[idx - jdx], w_[idx - jdx]) for jdx in range(1, m + 1)])
        w_[idx] = w_[idx - 1] + h * (f_val * coef).sum()
    return (t_, w_)


In [569]:
f = lambda t, y: y - t ** 2 + 1
AdamsBashforth(f, 0, 2, 0.5, 0.2, 4)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 array([0.5       , 0.82929333, 1.21407621, 1.64892202, 2.12728925,
        2.64105333, 3.18031413, 3.73301859, 4.28444241, 4.81659556,
        5.30750818]))

### Predictor-Corrector Method

# 

In [570]:
def AdamsMoulton(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
                 f_:np.ndarray,
                 t:float,
                 w:float,
                 w_estimated:float,
                 h:float,
                 m:int
                ) -> float:
    '''
    For internal use of Predictor-Corrector Method only
    '''
    coef = MultiStepCoef(m, False)
    f_cur = f(t, w_estimated) * coef[0]
    return w + h * (f_cur + (f_ * coef[1:]).sum())

def PredictorCorrector(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
       a:Union[float, int],
       b:Union[float, int],
       y_init:Union[float, int],
       h:Union[float, int]=None,
       m:int=None,
       N:int=None,
       helper:callable=RK4
       ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)

    coef = MultiStepCoef(m)
    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, ))
    w_[:m] = helper(f, a, b, y_init, h)[1][:m]
    
    for idx in range(m, N + 1):
        f_val = np.array([f(t_[idx - jdx], w_[idx - jdx]) for jdx in range(1, m + 1)])
        w_estimated = w_[idx - 1] + h * (f_val * coef).sum()
        w_[idx] = AdamsMoulton(f, f_val[:m - 1], t_[idx], w_[idx - 1], w_estimated, h, m)
    return (t_, w_)


### Milne-Simpson Predictor-Corrector

In [586]:
def MilneSimpsonPC(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
       a:Union[float, int],
       b:Union[float, int],
       y_init:Union[float, int],
       h:Union[float, int]=None,
       N:int=None,
       helper:callable=RK4
       ) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:
    if (h is None) and (N is None):
        raise ValueError("h and N cannot be None at the same time")
    elif h is None:
        h = (b - a) / N
    elif N is None:
        N = int((b - a) / h)


    t_, w_ = np.linspace(a, b, N + 1), np.ones((N + 1, ))
    w_[:4] = helper(f, a, b, y_init, h)[1][:4]
    
    for idx in range(4, N + 1):
        f_0, f_1 = f(t_[idx - 1], w_[idx - 1]), f(t_[idx - 2], w_[idx - 2])
        w_estimated = w_[idx - 4] + 4 * h * (2 * f_0 - f_1 + 2 * f(t_[idx - 3], w_[idx - 3])) / 3
        w_[idx] = w_[idx - 2] + h * (f(t_[idx], w_estimated) + 4 * f_0 + f_1) / 3
    return (t_, w_)

In [591]:
f = [
    lambda t, y: y / t - (y / t) ** 2,
    lambda t, y: 1 + y / t + (y / t) ** 2,
    lambda t, y: -(y + 1) * (y + 3),
    lambda t, y: -5 * y + 5 * t ** 2 + 2 * t
]
a = [1, 1, 0, 0]
b = [2, 3, 2, 1]
y_init = [1, 0, -2, 1 / 3]
h = [0.1, 0.2, 0.1, 0.1]

for idx in range(len(f)):
    print(MilneSimpsonPC(f[idx], a[idx], b[idx], y_init[idx], h[idx], helper=RK4)[1])


[1.         1.0042815  1.014952   1.02981334 1.04752889 1.06725997
 1.08842662 1.11065221 1.13364724 1.1572255  1.18122584]
[0.         0.22124571 0.48968417 0.81275216 1.19942245 1.6612615
 2.21346054 2.87648763 3.67836211 4.65847375 5.87375555]
[-2.         -1.90033209 -1.80262486 -1.70868768 -1.62004966 -1.53788255
 -1.46294935 -1.39563312 -1.33596376 -1.28370483 -1.23840789 -1.19950485
 -1.16634802 -1.1382809  -1.11465069 -1.09485532 -1.07833303 -1.06459376
 -1.05319474 -1.04376468 -1.03597247]
[0.33333333 0.21228299 0.16276546 0.16451654 0.2049417  0.2774108
 0.37637364 0.50008713 0.64594324 0.81371383 1.00215439]


## Chapter 5.7 Variable Step-Size MultiStep Methods
The Runge-Kutta-Fehlberg method is used for error control because at each step it provides,
at little additional cost, two approximations that can be compared and related to the local
truncation error. Predictor-corrector techniques always generate two approximations at each
step, so they are natural candidates for error-control adaptation.

In [572]:
def VariablePredictorCorrector(f:Callable[[Union[float, int], Union[float, int]], Union[float, int]],
       a:Union[float, int],
       b:Union[float, int],
       y_init:Union[float, int],
       h_max:Union[float, int],
       h_min:Union[float, int],
       m:int,
       n:int,
       delta_coef:float,
       helper:callable,
       tol:float=1e-6,) -> Tuple[np.ndarray[Union[float, int], Any], np.ndarray[Union[float, int], Any]]:

    AM_LTE = abs(MultiStepCoef(m + 1, False)[-1])
    sigma_coef = AM_LTE / (abs(MultiStepCoef(m + 1)[-1]) + AM_LTE)

    coef = MultiStepCoef(m)
    t_, w_ = [a], [y_init]
    h = h_max
    rk_computed = helper(f, h, t_, w_)
    flag = True
    last = False

    idx = m
    t = t_[-1] + h
    while flag:
        f_val = np.array([f(t_[idx - jdx], w_[idx - jdx]) for jdx in range(1, m + 1)])
        w_AB = w_[idx - 1] + h * (f_val * coef).sum()
        w_AM = AdamsMoulton(f, f_val[:m - 1], t, w_[idx - 1], w_AB, h, m)
        sigma = abs(w_AM - w_AB) * sigma_coef / h
        if sigma <= tol:
            t_.append(t)
            w_.append(w_AM)
            if last:
                flag = False
            else:
                idx += 1
                rk_computed = False
                if sigma <= 0.1 * tol or t_[idx - 1] + h > b:
                    delta = (tol / sigma) ** (1 / n) * delta_coef
                    h *= delta if delta <= 4 else 4
                    h = min(h, h_max)
                    if t_[idx - 1] + m * h > b:
                        h = (b - t_[idx - 1]) / m
                        last = True
                    rk_computed = helper(f, h, t_, w_)
                    idx += m - 1
        else:
            delta = (tol / sigma * delta_coef) ** (1 / n)
            h *= delta if delta >= 0.1 else 0.
            if h < h_min:
                return (np.array(t_), np.array(w_))
            if rk_computed:
                idx -= m - 1
            t_ = t_[:idx]
            w_ = w_[:idx]
            rk_computed = helper(f, h, t_, w_)
            idx += m - 1
        t = t_[-1] + h
    return (np.array(t_), np.array(w_))

### Helper Runge-Kutta Methods function

In [573]:
def RK4_(f, h, t_, w_):
    x_0, y_0 = t_[-1], w_[-1]
    x_, y_ = [x_0] * 4, [y_0] * 4
    for idx in range(1, 4):
        K_1 = h * f(x_0, y_0)
        K_2 = h * f(x_0 + h / 2, y_0 + K_1 / 2)
        K_3 = h * f(x_0 + h / 2, y_0 + K_2 / 2)
        K_4 = h * f(x_0 + h, y_0 + K_3)
        y_0 += (K_1 + 2 * K_2 + 2 * K_3 + K_4) / 6
        x_0 += h
        x_[idx] = x_0
        y_[idx] = y_0
    t_.extend(x_[1:])
    w_.extend(y_[1:])
    return True

def RK5_(f, h, t_, w_):
    x_0, y_0 = t_[-1], w_[-1]
    x_, y_ = [x_0] * 5, [y_0] * 5
    for idx in range(1, 5):
        K_1 = h * f(x_0, y_0)
        K_2 = h * f(x_0 + h / 2, y_0 + K_1 / 2)
        K_3 = h * f(x_0 + h / 2, y_0 + K_1 / 4 + K_2 / 4)
        K_4 = h * f(x_0 + h, y_0 - K_2 + 2 * K_3)
        K_5 = h * f(x_0 + 2 * h / 3, y_0 + 7 * K_1 / 27 + 10 * K_2 / 27 + K_4 / 27)
        K_6 = h * f(x_0 + h / 5, y_0 + 28 * K_1 / 625 - K_2 / 5 + 546 * K_3 / 625 + 54 * K_4 / 625 - 378 * K_5 / 625)
        y_0 += (K_1/ 24 + 5 * K_4 / 48 + 27 * K_5 / 56 + 125 * K_6 / 336)
        x_0 += h
        x_[idx] = x_0
        y_[idx] = y_0
    t_.extend(x_[1:])
    w_.extend(y_[1:])
    return True

In [577]:
# Exercise 1, 2, 3 for Section 5.5 and 5.7
# Some precision error compared to the answers may due to that Python take in account more precision
# and causes the step size becomes slightly different

f = [
    lambda t, y: t * np.exp(3 * t) - 2 * y,
    lambda t, y: 1 + (t - y) ** 2,
    lambda t, y: 1 + y / t,
    lambda t, y: np.cos(2 * t) + np.sin(3 * t),

    lambda t, y: (y / t) ** 2 + y / t,
    lambda t, y: np.sin(t) + np.exp(-t),
    lambda t, y: (y ** 2 + y) / t,
    lambda t, y: -t * y + 4 * t / y,

    lambda t, y: y / t - (y / t) ** 2,
    lambda t, y: 1 + y / t + (y / t) ** 2,
    lambda t, y: -(y + 1) * (y + 3),
    lambda t, y: (t + 2 * t ** 3) * y ** 3 - t * y
]

a = [0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0]
b = [1, 3, 2, 1, 1.2, 1, 3, 1, 4, 3, 3, 2]
y_init = [0, 1, 2, 1, 1, 0, -2, 1, 1, 0, -2, 1 / 3]
h_max_multi = [0.25, 0.25, 0.25, 0.25, 0.05, 0.2, 0.4, 0.2, 0.5, 0.5, 0.5, 0.5]
h_min_multi = [0.025] * 4 + [0.01] * 4 + [0.02] * 4
h_max_rkf = [0.25, 0.25, 0.25, 0.25, 0.05, 0.25, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
h_min_rkf = [0.05] * 4 + [0.02] * 4 + [0.05] * 4
tol = [10 ** (-4)] * 8 + [10 ** (-6)] * 4


pc_5 = []
pc_4 = []
rkf = []
for idx in range(len(f)):
    pc_5.append(VariablePredictorCorrector(f[idx], a[idx], b[idx], y_init[idx], h_max_multi[idx], h_min_multi[idx], 5, 5, 0.5, RK5_, tol[idx])[1][-1])
    pc_4.append(VariablePredictorCorrector(f[idx], a[idx], b[idx], y_init[idx], h_max_multi[idx], h_min_multi[idx], 4, 4, 0.5, RK4_, tol[idx])[1][-1])
    rkf.append(RKEmbedded(f[idx], a[idx], b[idx], RKF_rk, RKF_b, RKF_bp, RKF_c, y_init[idx], h_max_rkf[idx], h_min_rkf[idx], 4, 0.84, tol[idx])[1][-1])

pd.DataFrame(
    {
        "VariablePredictorCorrector Order 5":pc_5,
        "VariablePredictorCorrector Order 4":pc_4,
        "RKF":rkf

    }
)


print(rkf)
    


[3.2190497393722843, 2.5000005195700776, 5.386295800587069, 2.1179749897712514, 1.4675697102409346, 1.0918181629953474, -1.2000194527914543, 1.7018814295215738, 1.6762392507696966, 5.874105850766712, -1.004945024897321, 0.054345435085901464]


C:\Users\User\AppData\Local\Temp/ipykernel_27456/2359315489.py:29: RuntimeWarning: invalid value encountered in scalar divide
  sigma = abs(w_AM - w_AB) * sigma_coef / h
