In [81]:
import numpy as np
from typing import Tuple, Union

# Linear Systems of Equations

## Backward and Forward Substituition 
Given an augmented upper triangular matrix $U$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_n = \frac{u_{n, n+1}}{u_{n, n}}$$
$$x_i=\frac{1}{u_{i, i}}\biggl(u_{i, n+1}-\sum^{n}_{j=i+1}u_{i, j}x_{j}\biggr)$$
where $i=1,2,\cdots,n-1$

Given an augmented lower triangular matrix $L$ with the shape $n\times (n + 1)$, we can compute the solutions for the systems by formula below:
$$x_1 = \frac{l_{1, n+1}}{l_{1, 1}}$$
$$x_i=\frac{1}{l_{i, i}}\biggl(l_{i, n+1}-\sum^{i - 1}_{j=1}l_{i, j}x_{j}\biggr)$$


In [82]:
def backSub(U:np.ndarray) -> np.ndarray:
    N, M = U.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[N - 1][0] = U[N - 1][M - 1] / U[N - 1][N - 1]    
    for jdx in range(N - 2, -1, -1):
        x[jdx] = (U[jdx][M - 1] - np.sum(U[jdx, jdx + 1:N] @ x[jdx + 1:])) / U[jdx][jdx]
    return x

def forSub(L:np.ndarray) -> np.ndarray:
    N, M = L.shape
    x = np.zeros((N, 1), dtype=np.float64)
    x[0][0] = L[0][M - 1] / L[0][0]   
    for jdx in range(1, N):
        x[jdx] = (L[jdx][M - 1] - np.sum(L[jdx, :jdx] @ x[:jdx])) / L[jdx][jdx]
    return x

In [83]:
def forwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    return backSub(A_) if not return_A else (A_, backSub(A_))

def backwardElimination(A:np.ndarray, return_A:bool=False) -> Union[Tuple[np.ndarray, np.ndarray], np.ndarray]:
    '''
    Parameters:
    A: Augmented matrix of the system of equations Ax = b
    '''
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    for idx in range(N - 1, 0, -1):
        non_zero = np.nonzero(A_[:idx, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][::-1][0]
        A_[[idx, ptr]] = A_[[ptr, idx]]
            
        for jdx in range(idx - 1, -1, -1):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[0][0] == 0:
        raise ValueError("No Unique Solution Exists...")
    return forSub(A_) if not return_A else (A_, forSub(A_))


(array([[ 1., -1.,  2., -1., -8.],
       [ 0.,  2., -1.,  1.,  6.],
       [ 0.,  0., -1., -1., -4.],
       [ 0.,  0.,  0.,  2.,  4.]]), array([[-7.],
       [ 3.],
       [ 2.],
       [ 2.]]))
(array([[  2.        ,   0.        ,   0.        ,   0.        ,
        -14.        ],
       [ -0.0952381 ,   0.0952381 ,   0.        ,   0.        ,
          0.95238095],
       [  3.        ,  -3.        ,   7.        ,   0.        ,
        -16.        ],
       [  2.        ,  -2.        ,   3.        ,  -3.        ,
        -20.        ]]), array([[-7.],
       [ 3.],
       [ 2.],
       [ 2.]]))


In [92]:
A = np.array([
   [1, -1, 2, -1, -8],
   [2, -2, 3, -3, -20],
   [1, 1, 1, 0, -2],
   [1, -1, 4, 3, 4] 
], dtype=np.float32)

forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :4], A[:, -1])

(array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([[-7.],
        [ 3.],
        [ 2.],
        [ 2.]]),
 array([-7.,  3.,  2.,  2.], dtype=float32))

In [95]:
A = np.random.randint(-50, 50, 42).reshape(6, 7)
print(A)
forwardElimination(A), backwardElimination(A), np.linalg.solve(A[:, :6], A[:, -1])

[[-25  25  -5   5  28 -33  -5]
 [ 11  20 -39  49 -26 -46  -9]
 [-20  20 -49 -39  -6 -38  35]
 [ 25 -25 -29   2 -41 -37 -20]
 [-50 -23  31 -33 -45  20 -23]
 [ -1  31 -22  -1  19  41 -22]]


(array([[ 4.64557602],
        [ 7.1913326 ],
        [ 4.97678842],
        [-3.57324327],
        [-3.09624895],
        [-1.84246104]]),
 array([[ 4.64557602],
        [ 7.1913326 ],
        [ 4.97678842],
        [-3.57324327],
        [-3.09624895],
        [-1.84246104]]),
 array([ 4.64557602,  7.1913326 ,  4.97678842, -3.57324327, -3.09624895,
        -1.84246104]))

## Determinant of the Matrix
> If B is a matrix obtained by multiplying a row of A by some non-zero constant ß, then
> - det(B) = ß * det(A)
> 
> In other words, you can essentially 'factor out' a constant from a row by just pulling it out front of the determinant.
> If B is a matrix obtained by swapping two rows of A, then
> 
> - det(B) = -det(A)
> 
> If you swap rows, flip the sign.
> If B is a matrix obtained by adding a multiple of one row to another row in A, then
> 
> - det(B) = det(A)
> 
> The determinant doesn't change.

Reference:[https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix](https://stackoverflow.com/questions/2435133/what-is-the-best-algorithm-to-find-a-determinant-of-a-matrix)

The algorithm below implemented using the property that the determinant of the diagonal or triangular  matrix no matter lower or upper, the determinant is equal to $0$

So by using this property and the rule $(2\text{ and }3)$ above we come to the conclusion that $det(A)=(-1)^{m}\prod_{i}u_{i, i}$, where $u$ is the entry of the upper triangular matrix after reduce matrix $A$ to row echelon form and $m$ is the number of time we interchange the row.

In [84]:
def det(A:np.ndarray) -> float:
    N, M = A.shape
    A_ = np.copy(A).astype(float)
    p = 0
    for idx in range(N - 1):
        non_zero = np.nonzero(A_[idx:, idx])
        if not non_zero[0].size:
            raise ValueError("No Unique Solution Exists...")
        ptr = non_zero[0][0] + idx

        # Row interchange causes sign of determinant flips
        if ptr != idx:
            A_[[idx, ptr]] = A_[[ptr, idx]]
            p += 1
            
        # Addition between row does not change the determinant
        for jdx in range(idx + 1, N):
            m = A_[jdx][idx] / A_[idx][idx]
            A_[jdx] -= m * A_[idx]
            
    if A_[N - 1][N - 1] == 0:
        raise ValueError("No Unique Solution Exists...")
    
    return np.prod(np.diag(A_)) * (-1) ** p

In [85]:
A = np.array([
   [1, -1, 2, -1],
   [2, -2, 3, -3],
   [1, 1, 1, 0],
   [1, -1, 4, 3] 
], dtype=np.float32)
det(A), np.linalg.det(A)

(4.0, 4.0)

In [87]:
A = np.random.randint(1, 20, 16).reshape((4, 4))
det(A), np.linalg.det(A)

(-14454.0, -14454.00000000001)